@echo off
if %DEBUG_ECHO%=="debug" echo DEBUG: config 3 iniciado
rem cp3_config3.bat
rem este arquivo eh para ser preechido automaticamente

rem SET CAMINHO_ORIGEM=C:\_O_HDN2\OneDrive\_GAMES\KSP\_c3_dev\
set CAMINHO_DESTINO=\\HDNLIL-W10-PC\ksp\Ships\Script\ 
set CAMINHO_ORIGEM=C:\_O_HDN2\OneDrive\_GAMES\KSP\_c3_dev\ 
REM ATUALIZADO EM  
set CAMINHO_DESTINO=\\Hdnlil-w10-pc\hdnlil\Users\Carlos Amorim\Desktop\Kerbal Space Program Making History 1.4.2.2110\Ships\Script\ 
set CAMINHO_ORIGEM=C:\_O_HDN2\OneDrive\_GAMES\KSP\_c3_dev\ 
REM ATUALIZADO EM 31/08/2019  08:34 
set CAMINHO_DESTINO=\\Hdnlil-w10-pc\hdnlil\Users\Carlos Amorim\Desktop\Kerbal Space Program Making History 1.4.2.2110\Ships\Script\
set CAMINHO_ORIGEM=C:\_O_HDN2\OneDrive\_GAMES\KSP\_c3_dev\
REM ATUALIZADO EM 31/08/2019  08:39 
set CAMINHO_DESTINO_3=\\Ub18-pend-big\_compart\INSTALL_WIN\_KSP\Linux\Ships\Script\
set CAMINHO_ORIGEM_3=C:\_O_HDN2\OneDrive\_GAMES\KSP\_c3_dev\
set EXCLUSAO_AUTOMATICA=False
set NOME_CONFIG_SLOT_3=C3_EDIT_HDN2novo_PLAY_HDN3_120_LINUX
REM ATUALIZADO EM 02/09/2019  01:32
set CAMINHO_DESTINO_3=\\Ub18-pend-big\_compart\INSTALL_WIN\_KSP\Linux\Ships\Script\
set CAMINHO_ORIGEM_3=C:\_O_HDN2\OneDrive\_GAMES\KSP\_c3_dev\
set EXCLUSAO_AUTOMATICA=False
set NOME_CONFIG_SLOT_3=C3_EDIT_HDN2novo_PLAY_HDN3_120_LINUX
REM ATUALIZADO EM 02/09/2019  01:41
set CAMINHO_DESTINO_6=\\Ub18-pend-big\_compart\INSTALL_WIN\_KSP\Linux\Ships\Script\\
set CAMINHO_ORIGEM_6=C:\_O_HDN2\OneDrive\_GAMES\KSP\_c3_dev\\
set EXCLUSAO_AUTOMATICA=False
set NOME_CONFIG_SLOT_6=C3_EDIT_HDN2novo_PLAY_HDN3_120_LINUX
REM ATUALIZADO EM 02/09/2019  01:46
set CAMINHO_DESTINO_3=\\Ub18-pend-big\_compart\INSTALL_WIN\_KSP\Linux\Ships\Script\\
set CAMINHO_ORIGEM_3=C:\_O_HDN2\OneDrive\_GAMES\KSP\_c3_dev\\
set EXCLUSAO_AUTOMATICA=False
set NOME_CONFIG_SLOT_3=C3_EDIT_HDN2novo_PLAY_HDN3_120_LINUX
REM ATUALIZADO EM 02/09/2019  01:48
set CAMINHO_DESTINO_3=\\Ub18-pend-big\_compart\INSTALL_WIN\_KSP\Linux\Ships\Script\
set CAMINHO_ORIGEM_3=C:\_O_HDN2\OneDrive\_GAMES\KSP\_c3_dev\
set EXCLUSAO_AUTOMATICA=False
set NOME_CONFIG_SLOT_3=C3_EDIT_HDN2novo_PLAY_HDN3_120_LINUX
REM ATUALIZADO EM 02/09/2019  01:52
set CAMINHO_DESTINO_3=\\Ub18-pend-big\_compart\INSTALL_WIN\_KSP\Linux\Ships\Script\
set CAMINHO_ORIGEM_3=C:\_O_HDN2\OneDrive\_GAMES\KSP\_c3_dev\
set EXCLUSAO_AUTOMATICA=False
set NOME_CONFIG_SLOT_3=C3_EDIT_HDN2novo_PLAY_HDN3_120_LINUX
REM ATUALIZADO EM 02/09/2019  01:57
set CAMINHO_DESTINO_3=\\Ub18-pend-big\_compart\INSTALL_WIN\_KSP\Linux\Ships\Script\
set CAMINHO_ORIGEM_3=C:\_O_HDN2\OneDrive\_GAMES\KSP\_c3_dev\
set EXCLUSAO_AUTOMATICA=False
set NOME_CONFIG_SLOT_3=C3_EDIT_HDN2novo_PLAY_HDN3_120_LINUX
REM ATUALIZADO EM 02/09/2019  01:59
set CAMINHO_DESTINO_6=\\Ub18-pend-big\_compart\INSTALL_WIN\_KSP\Linux\Ships\Script\
set CAMINHO_ORIGEM_6=C:\_O_HDN2\OneDrive\_GAMES\KSP\_c3_dev\
set EXCLUSAO_AUTOMATICA=False
set NOME_CONFIG_SLOT_6=C3_EDIT_HDN2novo_PLAY_HDN3_120_LINUX
REM ATUALIZADO EM 02/09/2019  02:00
set umaporra=asdf
set CAMINHO_DESTINO_6=\\Ub18-pend-big\_compart\INSTALL_WIN\_KSP\Linux\Ships\Script\
set CAMINHO_ORIGEM_6=C:\_O_HDN2\OneDrive\_GAMES\KSP\_c3_dev\
set EXCLUSAO_AUTOMATICA=False
set NOME_CONFIG_SLOT_6=C3_EDIT_HDN2novo_PLAY_HDN3_120_LINUX
REM ATUALIZADO EM 02/09/2019  02:02
set CAMINHO_DESTINO_6=\\Ub18-pend-big\_compart\INSTALL_WIN\_KSP\Linux\Ships\Script\
set CAMINHO_ORIGEM_6=C:\_O_HDN2\OneDrive\_GAMES\KSP\_c3_dev\
set EXCLUSAO_AUTOMATICA=False
set NOME_CONFIG_SLOT_6=C3_EDIT_HDN2novo_PLAY_HDN3_120_LINUX
set "SLOT_PADRAO=6"
REM ATUALIZADO EM 02/09/2019  02:11
set CAMINHO_DESTINO_1=\\HDNLIL-W10-PC\ksp\Ships\Script\
set CAMINHO_ORIGEM_1=C:\_O_HDN2\OneDrive\_GAMES\KSP\_c3_dev\
set EXCLUSAO_AUTOMATICA=False
set NOME_CONFIG_SLOT_1=C3_TEST_HDN2new_PLAY_HDBIG_171_W10
set "SLOT_PADRAO=1"
REM ATUALIZADO EM 03/09/2019  09:36
set CAMINHO_DESTINO_1=\\Hdnbig-w7-pc\_nao_quero\___EXCLUIR\Kerbal Space Program Breaking Ground MULTi9\Ships\Script\
set CAMINHO_ORIGEM_1=C:\_O_HDN2\OneDrive\_GAMES\KSP\_c3_dev\
set EXCLUSAO_AUTOMATICA=False
set NOME_CONFIG_SLOT_1=C3_TEST_HDN2_PLAY_HDB_173_W7
set "SLOT_PADRAO=1"
REM ATUALIZADO EM 23/04/2020  11:34
set CAMINHO_DESTINO_2=\\Hdnbig-w7-pc\_nao_quero\___EXCLUIR\KSP Theres No Place Like Home 1.9.1.2788\Ships\Script\
set CAMINHO_ORIGEM_2=C:\_O_HDN2\OneDrive\_GAMES\KSP\_c3_dev\
set EXCLUSAO_AUTOMATICA=True
set NOME_CONFIG_SLOT_2=C3_TEST_HDN2_PLAY_HDB_191_W7
set "SLOT_PADRAO=2"
REM ATUALIZADO EM 27/04/2020  18:11
set CAMINHO_DESTINO_4=Z:\Ships\Script\
set CAMINHO_ORIGEM_4=C:\_O_HDN2\OneDrive\_GAMES\KSP\_c3_dev\
set EXCLUSAO_AUTOMATICA=True
set NOME_CONFIG_SLOT_4=C3_ED_HDN2_PLAY_HDB_1101_XUB
set "SLOT_PADRAO=4"
REM ATUALIZADO EM 05/12/2020  14:13
